services:
  db:
    image: postgres:15-alpine
    container_name: waygo_db_local
    restart: always
    environment:
      TZ: Asia/Tashkent
      POSTGRES_DB: waygo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - waygo_local_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d waygo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - waygo_local_net

  redis:
    image: redis:7-alpine
    container_name: waygo_redis_local
    restart: always
    environment:
      TZ: Asia/Tashkent
    volumes:
      - waygo_local_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - waygo_local_net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: waygo_backend_app_local
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      TZ: Asia/Tashkent
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/waygo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - waygo_local_net

  db-backup:
    image: prodrigestivill/postgres-backup-local:15
    container_name: waygo_db_backup_local
    restart: always
    volumes:
      - ./backups:/backups
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=waygo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SCHEDULING=true
      - BACKUP_NUM_KEEP=14
      - SCHEDULE=0 2 * * *
      - BACKUP_DIR=/backups
      - TZ=Asia/Tashkent
    networks:
      - waygo_local_net

networks:
  waygo_local_net:
    driver: bridge

volumes:
  waygo_local_postgres_data:
  waygo_local_redis_data:
