spring:
  application:
    name: waygo_backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/waygo_db
    username: postgres
    password: password # Replace with your local DB password
    driver-class-name: org.postgresql.Driver
  
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: mail.ssale.uz
    port: 465
    username: support@ssale.uz # Replace with your actual Ahost email
    password: YOUR_PASSWORD_HERE # Add your email password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    default-encoding: UTF-8

server:
  port: 8080

# JWT Configuration
waygo:
  jwt:
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    expiration: 86400000 # 24 hours in MS
  sms:
    # provider: ${SMS_PROVIDER:console} # Set to 'eskiz' to use real SMS service
    provider: ${SMS_PROVIDER:eskiz} # Set to 'eskiz' to use real SMS service
  eskiz:
    email: ${ESKIZ_EMAIL:temuryoldoshev10@gmail.com}
    password: ${ESKIZ_PASSWORD:0ko2ifH5jKWLLwZSoTlsaiXu3IIwM9CYcAJDroFg}
    from: ${ESKIZ_FROM:4546}
    baseUrl: https://notify.eskiz.uz/api/
  mail:
    provider: ${MAIL_PROVIDER:console} # SMTPlar tayyor bo'lgach 'smtp' ga o'zgartiramiz
